[config.wallpaper]
command = "swww"
arguments = ["img", "-t", "wave", "--transition-duration=3"]
set = true

[templates.pywalfox]
input_path = '~/.local/share/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.foot]
input_path = '~/.local/share/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.terminal]
input_path = '~/.local/share/matugen/templates/term_colors.txt'
output_path = '/tmp/term_colors.txt'
post_hook = '~/.local/share/scripts/change_term_colors.sh'

[templates.starship]
input_path = '~/.local/share/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = '~/.local/share/matugen/templates/vesktop.css'
output_path = '~/.var/app/dev.vencord.Vesktop/config/vesktop/settings/quickCss.css'

[templates.hyprland]
input_path = '~/.local/share/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.local/share/matugen/templates/mako.conf'
output_path = '~/.config/mako/mako.conf'
post_hook = 'makoctl reload'

[templates.slurp]
input_path = '~/.local/share/matugen/templates/screenshot.sh'
output_path = '~/.local/share/scripts/screenshot.sh'

[templates.tofi]
input_path = '~/.local/share/matugen/templates/tofi'
output_path = '~/.config/tofi/config'

[templates.eww]
input_path = '~/.local/share/matugen/templates/eww.scss'
output_path = '~/.config/eww/scss/colors.scss'

[templates.fzf]
input_path = '~/.local/share/matugen/templates/fzf.zsh'
output_path = '~/.config/zsh/fzf-style.zsh'

[templates.gtk3]
input_path = '~/.local/share/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.local/share/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/.local/share/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.local/share/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.tty]
input_path = '~/.local/share/matugen/templates/cmdline.conf'
output_path = '/tmp/cmdline_colors.conf'
post_hook = '{ sudo colorize-cmdline.sh && notify-send "Cmdline Updated" ":3" } &'
