format="""
[](bg:none fg:#c4c0ff)\
$username\
[](bg:#c4c0ff fg:#c7c4dc)\
$hostname\
[](bg:#c7c4dc fg:#c4c0ff)\
$directory\
[](bg:#c7c4dc fg:#c4c0ff)\
$git_branch\
[](bg:#c4c0ff fg:#c7c4dc)\
$cmd_duration\
[](bg:none fg:#c4c0ff)\
$line_break\
$character\
"""
add_newline = false 

# Prompt symbols 
[character]
success_symbol = "[](#c4c0ff)"
error_symbol = "[](#c7c4dc)"
vicmd_symbol = "[](#c7c4dc)"

[username]
disabled = true
show_always = true
format = "[  $user ](bg:#c4c0ff fg:#2c2960 bold)"

[hostname]
disabled = true
ssh_only = false
format = "[ 󰌽 $hostname ]( bg:#c7c4dc fg:#2f2e42 bold)"

[directory]
disabled =false
format = "[  $path ](bg:#c4c0ff fg:#2c2960 bold)"
truncation_length = 3
truncate_to_repo=true

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Videos" = ""
"iso" = "󰌽"
".config" = ""

[git_branch]
disabled =false
format = '[  $branch ](bg:#c7c4dc fg:#2f2e42 bold)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = true
format = '[ 󱑆 $duration ](bg:#c4c0ff fg:#2c2960 bold)'
