# acc
# .config/starship/dynamic.toml
format="""
[](bg:none fg:#CBA6F7)\
$username\
[](bg:#CBA6F7 fg:#cdd6f4)\
$hostname\
[](bg:#cdd6f4 fg:#CBA6F7)\
$directory\
[](bg:#cdd6f4 fg:#CBA6F7)\
$git_branch\
[](bg:#CBA6F7 fg:#cdd6f4)\
$cmd_duration\
[](bg:none fg:#CBA6F7)\
$line_break\
$character\
"""
add_newline = false 

# Prompt symbols 
[character]
success_symbol = "[ 󱞪](#CBA6F7)"
error_symbol = "[ 󱞪](#cdd6f4)"
vicmd_symbol = "[ 󱞪❯](#cdd6f4)"

[username]
disabled = true
show_always = true
format = "[  $user ](bg:#CBA6F7 fg:#1e1e2e bold)"

[hostname]
disabled = true
ssh_only = false
format = "[ 󰌽 $hostname ]( bg:#cdd6f4 fg:#1e1e2e bold)"

[directory]
disabled =false
format = "[  $path ](bg:#CBA6F7 fg:#1e1e2e bold)"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"iso" = "󰌽 "
".config" = ""

[git_branch]
disabled =false
format = '[  $branch ](bg:#cdd6f4 fg:#1e1e2e bold)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = true
format = '[ 󱑆 $duration ](bg:#CBA6F7 fg:#1e1e2e bold)'

